name: tugasku
description: Aplikasi manajemen tugas mahasiswa dengan metode SAW

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.3.3
  provider: ^6.1.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4
  google_fonts: ^6.2.1
  share_plus: ^10.0.0
  file_picker: ^8.1.2
  wakelock_plus: ^1.2.5
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/empty_tasks.png
    - assets/images/empty_calendar.png
    - assets/images/empty_priority.png
    - assets/icons/category_kuliah.png
    - assets/icons/category_praktikum.png
    - assets/icons/category_project.png
    - assets/icons/category_lainnya.png
